### ISSUE TITLE
Cannot download win32-x64-83_binding.node for "npm install" in rasa voice interface

### ISSUE THREAD

**Issue by srichaitanyatejaswi** [RasaHQ/rasa-voice-interface#34]
Hi,
I'm trying to build a voice chatbot and according to this [blog](https://blog.rasa.com/how-to-build-a-voice-assistant-with-open-source-rasa-and-mozilla-tools/), as an interface I'm using rasa-voice-interface. when trying to run 'npm install', It's not able to find a particular node-saas package "Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node":". I'm new to nodejs and npm. I'm just trying to follow this [blog](https://blog.rasa.com/how-to-build-a-voice-assistant-with-open-source-rasa-and-mozilla-tools/) and currently stuck here. 
Other steps I've implemented:
- found win32-x64-83_binding.node in another version of node-sass (6.0.1),changed the version in package.json, re-ran it and faced a compatibility issue.

Below is the command and the error I got.
```
C:\rasa-voice-interface>npm install  
> node-sass@4.13.0 install C:\rasa-voice-interface\node_modules\node-sass 
> node scripts/install.js  
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node 
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node":  
HTTP error 404 Not Found
```

Any help is appreciated.
Thanks

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by aeshky** [comment]
Thanks for your question @srichaitanyatejaswi. Please ask it in our forum instead: https://forum.rasa.com/
