### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by vinayg-intel** [RasaHQ/rasa-voice-interface#36]
I have built and run the UI and see the error on the browser: Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by sara-tagger** [comment]
Thanks for the issue, @jupyterjazz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by jupyterjazz** [comment]
Hi, 
[This thread](https://forum.rasa.com/t/webchat-failed-to-load-resource-net-err-connection-refused/20266) talks about the same error. I hope it's helpful. 

If it doesn't help, you should provide more information about the error (similar to what the author of the above-linked thread did).
