### ISSUE TITLE
Text is coming but sound is not coming from Rasa voice interface

### ISSUE THREAD

**Issue by kingafy** [RasaHQ/rasa-voice-interface#6]
My set up is working fine based on the blog provided for Rasa voice assistant. The text messages are also being displayed but I dont hear back the response text by the Rasa voice assistant. IS there any setting required to be changed?

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JustinaPetr** [comment]
Hey @kingafy You should hear the response automatically. The only thing you may check is if your browser has the access to your microphone.

I am running an update on this tutorial will check if everything is working and will get back to you asap.

**Comment by Bitseat** [comment]
This issue still persists. Can someone help me with fixing it?

**Comment by Bitseat** [comment]
solution here https://forum.rasa.com/t/rasa-voice-bot/26172/5
